server:
  port: 8762
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8069
          predicates:
            - Path=/quizapp/auth/**
        - id: user
          uri: http://localhost:8070
          predicates:
            - Path=/quizapp/user/**
        - id: question
          uri: http://localhost:8071
          predicates:
            - Path=/quizapp/question/**
        - id: quiz
          uri: http://localhost:8072
          predicates:
            - Path=/quizapp/quiz/**
        - id: result
          uri: http://localhost:8073
          predicates:
            - Path=/quizapp/result/**