eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8071

spring:
  application:
    name: question
  datasource:
    url: jdbc:mysql://localhost:3306/quizapp
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
      database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


