server:
  port: 8070
spring:
  application:
    name: user
  config:
    import: optional:configserver:http://localhost:8888zz
  datasource:
    url: jdbc:mysql://localhost:3306/quizapp
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


application:
  config:
    result-url: http://localhost:8762/quizapp/result