server:
  port: 8070
spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/quizapp
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect