spring:
  application:
    name: auth
server:
  port: 8069
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

application:
  config:
    user-url: http://localhost:8762/quizapp/user