server:
  port: 8072
spring:
  application:
    name: quiz
  datasource:
    url: jdbc:mysql://localhost:3306/quizapp
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

application:
  config:
    question-url: http://localhost:8071/quizapp/question